# Generated by Django 4.0.1 on 2022-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogisticdetail',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
