# Generated by Django 4.0.1 on 2022-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindashboard', '0002_transferlogisticdetail_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogisticdetail',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
