# Generated by Django 4.0.1 on 2022-07-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindashboard', '0003_transferlogisticdetail_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogisticdetail',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
