# Generated by Django 4.0.1 on 2022-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindashboard', '0004_transferlogisticdetail_shipped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('warehouse_deliveryParty', 'warehouse_deliveryParty'), ('warehouse_marking', 'warehouse_marking'), ('warehouse_items', 'warehouse_items'), ('warehouse_verify', 'warehouse_verify'), ('stuffing_container', 'stuffing_container')],
                'default_permissions': (),
            },
        ),
    ]
