# Generated by Django 4.0.1 on 2022-07-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindashboard', '0004_transferlogisticdetail_shipped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('warehouse.delivery_party', 'warehouse.delivery_party'), ('warehouse.marking', 'warehouse.marking'), ('warehouse.items', 'warehouse.items'), ('warehouse.verify', 'warehouse.verify'), ('stuffing.container', 'stuffing.container')],
                'default_permissions': (),
            },
        ),
    ]
